

export default function Invoice() {
    return (
        <>
            <section className="p-8">
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
                <p>Invoice no</p>
            </section>
        </>
    );
}